name: Reusable - Check Implementation Notes
on: { workflow_call: {} }
jobs:
  check-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request?.body || '';
            if (!/### Implementation Notes/i.test(body)) {
              core.setFailed('PR body must include "### Implementation Notes".');
            }